{
  "CVE Code": "CVE-2021-3116",
  "Published": "2021-01-11T05:00:49",
  "Updated": "2024-08-03T16:45:51.254Z",
  "Description": "before_upstream_connection in AuthPlugin in http/proxy/auth.py in proxy.py before 2.3.1 accepts incorrect Proxy-Authorization header data because of a boolean confusion (and versus or).",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://cardaci.xyz/advisories/2021/01/10/proxy.py-2.3.0-broken-basic-authentication/",
    "https://github.com/abhinavsingh/proxy.py/pull/482/commits/9b00093288237f5073c403f2c4f62acfdfa8ed46",
    "https://pypi.org/project/proxy.py/2.3.1/#history"
  ]
}