{
  "CVE Code": "CVE-2023-50782",
  "Published": "2024-02-05T20:45:49.705Z",
  "Updated": "2025-06-17T21:29:24.715Z",
  "Description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
  "ProblemTypes": [
    "Observable Timing Discrepancy"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "3.2"
      ]
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat Ansible Automation Platform 2",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat Enterprise Linux 7",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat Enterprise Linux 8",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat Enterprise Linux 8",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat Enterprise Linux 9",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat Satellite 6",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "versions": []
    }
  ],
  "Reference": [
    "https://access.redhat.com/security/cve/CVE-2023-50782",
    "https://bugzilla.redhat.com/show_bug.cgi?id=2254432"
  ]
}