{
  "CVE Code": "CVE-2019-20431",
  "Published": "2020-01-27T04:19:58",
  "Updated": "2024-08-05T02:39:09.989Z",
  "Description": "In the Lustre file system before 2.12.3, the ptlrpc module has an osd_map_remote_to_local out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. osd_bufs_get in the osd_ldiskfs module does not validate a certain length value.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "http://wiki.lustre.org/Lustre_2.12.3_Changelog",
    "http://lustre.org/",
    "https://jira.whamcloud.com/browse/LU-12612",
    "https://review.whamcloud.com/#/c/36273/"
  ]
}