{
  "CVE Code": "CVE-2014-2667",
  "Published": "2014-11-16T01:00:00",
  "Updated": "2024-08-06T10:21:36.046Z",
  "Description": "Race condition in the _get_masked_mode function in Lib/os.py in Python 3.2 through 3.5, when exist_ok is set to true and multiple threads are used, might allow local users to bypass intended file permissions by leveraging a separate application vulnerability before the umask has been set to the expected value.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "http://www.openwall.com/lists/oss-security/2014/03/28/15",
    "http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html",
    "https://security.gentoo.org/glsa/201503-10",
    "http://www.openwall.com/lists/oss-security/2014/03/30/4",
    "http://bugs.python.org/issue21082",
    "http://www.openwall.com/lists/oss-security/2014/03/29/5",
    "http://lists.opensuse.org/opensuse-updates/2014-05/msg00007.html",
    "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
  ]
}