{
  "CVE Code": "CVE-2022-23571",
  "Published": "2022-02-04T22:32:34.000Z",
  "Updated": "2025-04-23T19:07:57.657Z",
  "Description": "Tensorflow is an Open Source Machine Learning Framework. When decoding a tensor from protobuf, a TensorFlow process can encounter cases where a `CHECK` assertion is invalidated based on user controlled arguments, if the tensors have an invalid `dtype` and 0 elements or an invalid shape. This allows attackers to cause denial of services in TensorFlow processes. The fix will be included in TensorFlow 2.8.0. We will also cherrypick this commit on TensorFlow 2.7.1, TensorFlow 2.6.3, and TensorFlow 2.5.3, as these are also affected and still in supported range.",
  "ProblemTypes": [
    "CWE-617: Reachable Assertion"
  ],
  "Affected": [
    {
      "vendor": "tensorflow",
      "product": "tensorflow",
      "versions": [
        ">= 2.7.0, < 2.7.1",
        ">= 2.6.0, < 2.6.3",
        "< 2.5.3"
      ]
    }
  ],
  "Reference": [
    "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-j3mj-fhpq-qqjj",
    "https://github.com/tensorflow/tensorflow/commit/5b491cd5e41ad63735161cec9c2a568172c8b6a3"
  ]
}