{
  "CVE Code": "CVE-2023-6110",
  "Published": "2024-11-17T10:22:34.776Z",
  "Updated": "2024-12-05T20:30:27.043Z",
  "Description": "A flaw was found in OpenStack. When a user tries to delete a non-existing access rule in it's scope, it deletes other existing access rules which are not associated with any application credentials.",
  "ProblemTypes": [
    "Improper Handling of Structural Elements"
  ],
  "Affected": [
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 17.1 for RHEL 8",
      "versions": [
        "0:5.5.2-17.1.20230829213816.el8ost"
      ]
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 17.1 for RHEL 9",
      "versions": [
        "0:5.5.2-17.1.20230829210830.el9ost"
      ]
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 16.1",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 16.2",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 17.0",
      "versions": []
    },
    {
      "vendor": "Red Hat",
      "product": "Red Hat OpenStack Platform 18.0",
      "versions": []
    }
  ],
  "Reference": [
    "https://access.redhat.com/errata/RHSA-2024:2737",
    "https://access.redhat.com/errata/RHSA-2024:2769",
    "https://access.redhat.com/security/cve/CVE-2023-6110",
    "https://bugzilla.redhat.com/show_bug.cgi?id=2212960",
    "https://code.engineering.redhat.com/gerrit/gitweb?p=python-openstackclient.git;a=commit;h=7a7c364bdd7b2cd2b56e73724110710a68d58abf",
    "https://review.opendev.org/c/openstack/python-openstackclient/+/888697"
  ]
}