{
  "CVE Code": "CVE-2023-25399",
  "Published": "2023-07-05T00:00:00",
  "Updated": "2024-08-02T11:18:36.341Z",
  "Description": "A refcounting issue which leads to potential memory leak was discovered in scipy commit 8627df31ab in Py_FindObjects() function. Note: This is disputed as a bug and not a vulnerability. SciPy is not designed to be exposed to untrusted users or data directly.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://github.com/scipy/scipy/issues/16235",
    "https://github.com/scipy/scipy/pull/16397",
    "http://www.square16.org/achievement/cve-2023-25399/",
    "https://github.com/scipy/scipy/issues/16235#issuecomment-1625361328"
  ]
}