{
  "CVE Code": "CVE-2020-15523",
  "Published": "2020-07-04T22:54:00",
  "Updated": "2024-08-04T13:15:20.864Z",
  "Description": "In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in cases where CPython is embedded in a native application. This occurs because python3X.dll may use an invalid search path for python3.dll loading (after Py_SetPath has been used). NOTE: this issue CANNOT occur when using python.exe from a standard (non-embedded) Python installation on Windows.",
  "ProblemTypes": [
    "n/a"
  ],
  "Affected": [
    {
      "vendor": "n/a",
      "product": "n/a",
      "versions": [
        "n/a"
      ]
    }
  ],
  "Reference": [
    "https://bugs.python.org/issue29778",
    "https://github.com/python/cpython/pull/21297",
    "https://security.netapp.com/advisory/ntap-20210312-0004/"
  ]
}